RGB_MATRIX_SLEEP = yes
RAW_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no  # WICHTIG: Das schaltet 0x000c und 0x0080 aus!
VIA_ENABLE = no
NKRO_ENABLE = no
